# Generated by Django 2.0.3 on 2018-06-03 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Application name')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Api key creation date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('os', models.CharField(choices=[('a', 'Android'), ('i', 'iOS')], max_length=1)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ApiKey')),
            ],
        ),
        migrations.CreateModel(
            name='TestAB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(editable=False, max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('name', models.TextField()),
                ('number', models.IntegerField(default=0)),
                ('track', models.TextField(default='')),
                ('is_processed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TestAB')),
            ],
        ),
    ]
