# Generated by Django 2.0.3 on 2018-06-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testab',
            name='category',
            field=models.CharField(max_length=1),
        ),
    ]
